# Generated by Django 4.2.7 on 2023-12-03 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "Фотография новости",
                "verbose_name_plural": "Фотография новостей",
            },
        ),
    ]
